= Overview

This is a maven plugin that wraps - https://github.com/lvc/japi-compliance-checker

This plugin uses the perl scripts and components of japi-compliance-checker directly. So japi-compliance-checker has to be installed and available on your $PATH.

NOTE: If this plugin is run on a machine where japi-compliance-checker is not installed. A warning message will be seen, highlighting that the japi-compliance-checker is not available.


=== What it does

It allows us to better detect breaking changes of binary compatibility, this plugin enforces, that we only allow breaking changes, when there has been a change to the "MinorVersion”. 

NOTE: The above is assuming the following maven version format : ( see also https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855) 

<MajorVersion>.<MinorVersion>.<IncrementalVersion>

= Install

* JDK or OpenJDK - development files
* Maven
* Perl 5
* https://github.com/lvc/japi-compliance-checker#install

$git clone git@github.com:lvc/japi-compliance-checker.git
$cd japi-compliance-checker/

== Linxu

```
sudo make install prefix=/usr
```

== Mac

=== Permissions

set the approximate permission
[source,shell script]
----
$chmod -R 775 <path>
----

=== Path 

Add the japi-compliance-checker to your path

for example on a mac if you have installed it to ~/projects/japi-compliance-checker

[source,shell script]
----
$vi ~/.profile
----

add the following:

[source,shell script]
----
export PATH="$PATH:~/projects/japi-compliance-checker"
----

= Configuration

|===
| parameter  | default value | Example | Required / Optional

| expression
| japi-compliance-checker.pl -lib NAME %s %s
|
| optional

| referenceVersion
| <x>.<y>.0
| 5.20.120
| optional

| binaryCompatibilityPercentageRequired
| 100
|
| optional

|===

=== Reference Version

If you specify a reference version this will be used instead of the default reference version. If the reference version you provide is not availible in maven central, an error will be reported. 
Hence if no reference version is provided then the default version is used. The default version is <x>.<y>.0 version, for example assume that you where on 5.20.143-SNAPSHOT then this would be checked ( by default ) against 5.20.0, If 5.20.0 does not exist in maven central, then an error will be reported.

=== Expression

`japi-compliance-checker.pl -lib NAME %s %s`
the %s are the first and second jars, 
* first jar - reference version
* second jar - current project version

These jar will be resolved at runtime of the plugin.

This `expression`, is the expression that is passed directly to japi-compliance-checker.pl, for more information on the options see https://github.com/lvc/japi-compliance-checker, or run:

```
japi-compliance-checker.pl -help
````

=== Binary Compatibility Percentage Required

When the `japi-compliance-checker.pl` is run, it provides the `binary compatibility` as a percentage, if the percentage that is reported is lower than the percentage you set, the validation will fail and a link will be provided to an html a report. By default this is set to 100%.

== Maven

[source,xml]
----
<plugin>
    <groupId>software.chronicle</groupId>
    <artifactId>binary-compatibility-enforcer-plugin</artifactId>
    <version>1.0.0</version>
    <executions>
        <execution>
            <phase>verify</phase>
            <goals>
                <goal>enforcer</goal>
            </goals>
            <configuration>
                <!-- the version that it checks against -->
                <!-- if not set it will check against the <x>.<y>.0 version -->
                <referenceVersion>2.20.2</referenceVersion>

                <expression>japi-compliance-checker.pl -lib NAME %s %s</expression>

            </configuration>
        </execution>
    </executions>
</plugin>
----

